image:
  repository: jellyfin/jellyfin
  tag: latest
  pullPolicy: IfNotPresent

nodeSelector:
  kubernetes.io/hostname: apple-pi

resources:
  requests:
    memory: 512Mi
    cpu: 250m
  limits:
    memory: 6Gi
    cpu: "4"

storage:
  configSize: 5Gi
  storageClassName: local-path
  mediaHostPath: /mnt/usb-storage/media

publishedServerUrl: "http://jellyfin.local"

ingress:
  hosts:
    - jellyfin.local
    - 192.168.1.100
    - 192.168.1.101
    - 192.168.1.102
