apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
  namespace: jellyfin
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: jellyfin-config
  resources:
    requests:
      storage: {{ .Values.storage.configSize }}
