apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: jellyfin
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "jellyfin.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 8096
      targetPort: 8096
      protocol: TCP
  type: ClusterIP
