apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: pihole
  chart:
    spec:
      chart: ./charts/pihole
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      reconcileStrategy: Revision
  install:
    createNamespace: true
  upgrade:
    cleanupOnFail: true
