image:
  repository: pihole/pihole
  tag: "2026.02.0"
  pullPolicy: IfNotPresent

hostNetwork: true
dnsPolicy: ClusterFirstWithHostNet

nodeSelector:
  hostname: pumpkin-pi

env:
  TZ: "UTC"
  WEBPASSWORD: ""
  FTLCONF_webserver_api_password: ""
  FTLCONF_dns_upstreams: "8.8.8.8;8.8.4.4"
  FTLCONF_dns_listeningMode: "ALL"
  FTLCONF_webserver_port: "8080"
  FTLCONF_dhcp_active: "true"
  FTLCONF_dhcp_start: "192.168.1.2"
  FTLCONF_dhcp_end: "192.168.1.253"
  FTLCONF_dhcp_router: "192.168.1.254"
  FTLCONF_dhcp_leaseTime: "24h"

resources:
  requests:
    memory: 128Mi
    cpu: 100m
  limits:
    memory: 256Mi
    cpu: 500m

ingress:
  host: pihole.local

service:
  webPort: 8080

mdns:
  hostname: pihole.local
  ip: "192.168.1.102"
