apiVersion: v1
kind: Service
metadata:
  name: pihole-web
  namespace: pihole
spec:
  selector:
    app: pihole
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.service.webPort }}
      targetPort: {{ .Values.service.webPort }}
      protocol: TCP
