apiVersion: v1
kind: Service
metadata:
  name: pihole-web
  namespace: pihole
  labels:
    {{- include "pihole.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "pihole.selectorLabels" . | nindent 4 }}
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.service.webPort }}
      targetPort: {{ .Values.service.webPort }}
      protocol: TCP
