apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ihatemoney-data
  namespace: ihatemoney
  labels:
    {{- include "ihatemoney.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: ihatemoney-data
  resources:
    requests:
      storage: {{ .Values.storage.size }}
