all:
  children:
    servers:
      hosts:
        TheBakery:
          ansible_host: 192.168.1.100
    agents:
      hosts:
        ApplePi:
          ansible_host: 192.168.1.101
        PumpkinPi:
          ansible_host: 192.168.1.102
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    ansible_python_interpreter: /usr/bin/python3
