apiVersion: v1
kind: PersistentVolume
metadata:
  name: splitwise-sync-data
  labels:
    {{- include "splitwise-sync.labels" . | nindent 4 }}
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /mnt/usb-storage/splitwise-sync-data
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - apple-pi
